### ISSUE TITLE
There is no tag which refers release 0.1.0 available in Maven

### ISSUE THREAD

**Issue by konczak** [lukashinsch/spring-boot-actuator-user-agent-metrics#8]
Hi,
I've found out this repo and think it is cool - I tried it and after some confusions I found out how it works.

One thing on which I felt in the beginning - was that I assumed that master branch matches released version in Maven repo (due to missing tags) while it isn't.
I spent an hour looking for reason why it is calculating all requests - not only specified url-pattern.

Best regards and thanks for the solution.

**Comment by lukashinsch** [comment]
Hi,
sorry for the delay. I'm glad you could make some use of this little library. I'm afraid I neglected to setup proper tagging for the release, something I will fix when I get some time. Sorry about the confusion.
Best regards

**Comment by lukashinsch** [comment]
just created the missing tag(s) and released the unpublished changes as 0.1.1 to maven central

**Comment by konczak** [comment]
Thank you - now it is easier to understood differences:)
